POST http://localhost:8080/schedule
Content-Type: application/json

{
  "sunday": true,
  "monday": true,
  "tuesday": true,
  "wednesday": true,
  "thursday": true,
  "friday": true,
  "saturday": true,
  "start_hours": 15,
  "start_minutes": 11,
  "end_hours": 15,
  "end_minutes": 12,
  "url": "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio2_mf_p"
}

###

GET http://localhost:8080/schedule

###
